services:
  subtitle-tool:
    image: jagernb/mkvass:${MKVASS_TAG:-latest}
    container_name: subtitle-tool
    ports:
      - "8083:8080"
    volumes:
      # 把你的视频目录挂载到容器的 /media
      - ./media:/media
    environment:
      - MEDIA_DIR=/media
      - PORT=8080
      - DEFAULT_OUTPUT_DIR=output
      - PGS_CONVERTER_CMD=mkvtool
      - PGS_FONT_DIR=/usr/share/fonts/truetype/dejavu
      - PGS_FRAMERATE=23.976
      - PGS_RESOLUTION=1920*1080
    restart: unless-stopped
