services:
  subtitle-tool:
    image: jagernb/mkvass:${MKVASS_TAG:-latest}
    container_name: subtitle-tool
    ports:
      - "8083:8080"
    volumes:
      # 把你的视频目录挂载到容器的 /media
      - ./media:/media
    environment:
      - MEDIA_DIR=/media
      - PORT=8080
      - DEFAULT_OUTPUT_DIR=output
      - ASS_TO_PGS_CMD=
      - ASS_TO_PGS_FONT_DIR=/app/ass_to_pgs/font
      - ASS_TO_PGS_FRAMERATE=23.976
      - ASS_TO_PGS_RESOLUTION=1080p
    restart: unless-stopped
